README.md
First version of the README with basic information about what we know for now. :)
=> First README content. Close #7

.gitignore, .travis.yml, CODE_OF_CONDUCT.md, MANIFEST.in, Makefile, README.rst, tox.ini
=> Add travis and tox configuration.

CHANGELOG.rst, dev-requirements.txt, pollbot/tasks/releasenotes.py, pollbot/views/release.py, tests/test_tasks.py, tests/test_views.py
=> Add the releasenotes-published bot.

CHANGELOG.rst, pollbot/tasks/archives.py, pollbot/views/release.py, tests/test_tasks.py, tests/test_views.py
=> A bot to check that a build has been published in archive.mozilla.org

api.yaml, dev-requirements.txt, tests/test_oas.py
I figured it would be easier to discuss #1 if we started with an OAS spec for #12.
=> First draft OAS for #12

MANIFEST.in, pollbot/app.py, pollbot/contribute.yaml, pollbot/views/utilities.py, tests/test_oas.py, tests/test_views.py
=> Add the contribute.json endpoint.

CHANGELOG.rst, pollbot/app.py, pollbot/tasks/product_details.py, pollbot/views/release.py, tests/test_tasks.py, tests/test_views.py
=> Add the product-details tasks and endpoint

pollbot/app.py, pollbot/tasks/archives.py, pollbot/tasks/bedrock.py, pollbot/tasks/product_details.py, pollbot/views/release.py, tests/test_tasks.py, tests/test_views.py
=> Add download-links tasks and endpoint.

CHANGELOG.rst, pollbot/app.py, setup.py, tests/test_cors.py
=> Add CORS support.

pollbot/api.yaml, pollbot/app.py, pollbot/views/home.py, setup.py, tests/test_cors.py, tests/test_views.py
=> Serve a Swagger UI documentation.

pollbot/app.py, pollbot/middlewares.py, tests/test_views.py
=> Make sure error responses are JSON responses

pollbot/tasks/__init__.py, pollbot/tasks/archives.py, pollbot/tasks/bedrock.py, pollbot/tasks/product_details.py, tests/test_tasks.py
=> Use the PollBot User-Agent for tasks.

pollbot/app.py, pollbot/middlewares.py, pollbot/tasks/__init__.py, pollbot/tasks/archives.py, pollbot/tasks/bedrock.py, pollbot/tasks/product_details.py, pollbot/views/utilities.py, tests/test_tasks.py, tests/test_views.py
=> Add heartbeat and lbheartbeat endpoints.

pollbot/app.py, pollbot/views/utilities.py, tests/test_views.py
=> Add __version__ endpoint.

Dockerfile, Makefile, circle.yml, pollbot/__main__.py, scripts/run-tests.sh
=> Add a Dockerfile

pollbot/api.yaml, pollbot/app.py, pollbot/middlewares.py, pollbot/tasks/bedrock.py, pollbot/views/release.py, tests/test_tasks.py, tests/test_views.py
=> Add the get_release task and view.

CHANGELOG.rst, pollbot/api.yaml, pollbot/app.py, pollbot/tasks/product_details.py, pollbot/views/product.py, tests/test_tasks.py, tests/test_views.py
=> Add a ongoing-version endpoint.

pollbot/tasks/bedrock.py, pollbot/utils.py, tests/test_tasks.py
=> Add support for other release channels

pollbot/tasks/archives.py, pollbot/tasks/bedrock.py, pollbot/tasks/product_details.py, pollbot/utils.py, tests/test_tasks.py
=> Add nightly checks.

API_CHANGELOG.rst, pollbot/__init__.py, pollbot/api.yaml, pollbot/app.py, pollbot/middlewares.py, pollbot/tasks/archives.py, pollbot/views/release.py, tests/test_views.py
=> Add a view with the list of checks for each release channel.

pollbot/middlewares.py, tests/test_views.py
=> Redirect URL ending with a / to URLs without a trailing slash.

API_CHANGELOG.rst, CHANGELOG.rst, pollbot/middlewares.py, tests/test_views.py
Fixes #43 
Paired with @leplatrem
=> Add Cache-Control headers (fixes #43)

pollbot/views/home.py, tests/test_views.py
=> Fix doc URL in the home page.

pollbot/api.yaml
=> Add documentation for the /product/version endpoint.

CHANGELOG.rst, pollbot/views/release.py, tests/test_views.py
=> Handle aiohttp.ClientError.

CHANGELOG.rst, pollbot/tasks/archives.py, tests/test_tasks.py
=> Handle Archive CDN errors.

pollbot/utils.py, pollbot/views/decorators.py, pollbot/views/release.py, tests/test_views.py
=> Protect tasks against wrong version numbers.

API_CHANGELOG.rst, CHANGELOG.rst, pollbot/__init__.py, pollbot/api.yaml, pollbot/app.py, pollbot/tasks/balrog.py, pollbot/views/release.py, pollbot/views/utilities.py, tests/test_tasks.py, tests/test_views.py
=> Add balrog task and endpoint.

pollbot/tasks/__init__.py, pollbot/tasks/product_details.py, tests/test_tasks.py
=> Missing status with affirmative sentence in details

API_CHANGELOG.rst, CHANGELOG.rst, pollbot/api.yaml, pollbot/app.py, pollbot/tasks/buildhub.py, pollbot/views/release.py, pollbot/views/utilities.py, tests/test_tasks.py, tests/test_views.py
=> Add Buildhub checks.

API_CHANGELOG.rst, CHANGELOG.rst, pollbot/api.yaml, pollbot/app.py, pollbot/tasks/archives.py, pollbot/views/release.py, tests/test_tasks.py, tests/test_views.py
=> Add partner-repacks tasks and endpoint.

API_CHANGELOG.rst, CHANGELOG.rst, pollbot/api.yaml, pollbot/app.py, pollbot/tasks/crash_stats.py, pollbot/views/release.py, pollbot/views/utilities.py, tests/test_tasks.py, tests/test_views.py
=> Add Crash Stat uptake task.

pollbot/tasks/balrog.py, tests/test_tasks.py, tests/test_views.py
Fixes #106 
Based on #108 (please merge it fist and then I will rebase this one on top of it.)
=> Validate balrog rule for all platforms. 

API_CHANGELOG.rst, CHANGELOG.rst, pollbot/api.yaml, pollbot/app.py, pollbot/exceptions.py, pollbot/tasks/__init__.py, pollbot/tasks/telemetry.py, pollbot/views/release.py, pollbot/views/utilities.py, tests/test_tasks.py, tests/test_views.py
=> Add Telemetry Update Parket uptake task.

CHANGELOG.rst, pollbot/tasks/balrog.py, tests/test_tasks.py, tests/test_views.py
=> Deduplicate Balrog build IDs.

pollbot/tasks/crash_stats.py, pollbot/tasks/telemetry.py, tests/test_tasks.py
=> Display uptake in percentages.

CHANGELOG.rst, pollbot/tasks/telemetry.py, tests/test_tasks.py
=> Handle Telemetry Empty results

CHANGELOG.rst, pollbot/views/release.py, tests/test_views.py
=> Add support for TaskError url.

CHANGELOG.rst, pollbot/views/home.py, tests/test_views.py
=> Add the list of availables products.

CHANGELOG.rst, pollbot/tasks/buildhub.py
=> Use Buildhub prod.

pollbot/tasks/buildhub.py
=> Buildhub error URL when build was not found.

CHANGELOG.rst, pollbot/tasks/bedrock.py, tests/test_tasks.py
=> Add support for new beta bedrock download-links URL.

pollbot/tasks/bedrock.py, tests/test_tasks.py
=> Do not follow redirects.

CHANGELOG.rst, pollbot/tasks/telemetry.py, tests/test_tasks.py, tests/test_views.py
=> Reuse QUERY for NIGHTLY telemetry.

API_CHANGELOG.rst, CHANGELOG.rst, pollbot/api.yaml, pollbot/app.py, pollbot/tasks/bouncer.py, pollbot/utils.py, pollbot/views/release.py, pollbot/views/utilities.py, tests/test_tasks.py, tests/test_utils.py, tests/test_views.py
=> Add bouncer checks and endpoints.

CHANGELOG.rst, pollbot/tasks/archives.py, tests/test_tasks.py
=> Read the correct locale file for release candidates.

CHANGELOG.rst, pollbot/views/release.py, tests/test_views.py
=> Order checks so that non actionable checks show at the end.

pollbot/__init__.py, pollbot/api.yaml, pollbot/tasks/archives.py, pollbot/tasks/balrog.py, pollbot/tasks/bedrock.py, pollbot/tasks/bouncer.py, pollbot/tasks/buildhub.py, pollbot/tasks/product_details.py, pollbot/tasks/telemetry.py, pollbot/views/decorators.py, pollbot/views/release.py, tests/test_tasks.py, tests/test_views.py
=> Add support for devedition checks.

pollbot/tasks/balrog.py, tests/test_tasks.py
=> Fix Balrog beta and devedition version comparison.

CHANGELOG.rst, pollbot/tasks/archives.py, tests/test_views.py
=> Use the DEVEDITION tag for the Archive check.

CHANGELOG.rst, dev-requirements.txt, pollbot/api.yaml, pollbot/app.py, pollbot/tasks/telemetry.py, pollbot/views/release.py, tests/test_tasks.py, tests/test_views.py
- BETA: https://sql.telemetry.mozilla.org/queries/50461/source#table
- DEVEDITION: https://sql.telemetry.mozilla.org/queries/50463/source#table
=> Grab Telemetry Uptake using main summary.

CHANGELOG.rst, pollbot/tasks/telemetry.py
=> Calculate the value of yesterday in the telemetry side.

CHANGELOG.rst, Makefile, README.rst, pollbot/app.py, pollbot/tasks/telemetry.py, scripts/run-tests.sh, tests/test_app.py, tests/test_tasks.py, tox.ini
=> Only search for queries created by the pollbot current user.

Makefile
=> The 'version-file' entry in the Makefile now creates a version.json compatible with Dockerflow

CHANGELOG.rst, requirements.txt, setup.py
=> latest pyyaml

pollbot/__init__.py, pollbot/tasks/archives.py, pollbot/tasks/balrog.py, pollbot/tasks/bedrock.py, pollbot/tasks/bouncer.py, pollbot/tasks/buildhub.py, pollbot/tasks/product_details.py, pollbot/views/release.py, pollbot/views/utilities.py, tests/test_tasks.py, tests/test_views.py
Resolves #51 
Proof-of-concept addition of a Thunderbird product to PollBot. State: functional
I plan to do some cleanup,and try to make the changes themselves more consistent in style. I'm sure some tests will fail too.
=> Thunderbird support in PollBot

pollbot/api.yaml
-------------
!!! HELLO !!!
-------------
Thank you for taking the time to contribute, we really appreciate it.
If it is your first time, please know that you are really welcome !!
--------------------------
Are you adding a new task?
--------------------------
If yes, you might want to have a look at this documentation and examples
https://github.com/mozilla/PollBot/wiki/Adding-a-task-for-PollBot
------------------------
DELETE EVERYTHING BEFORE
------------------------
Adding a task todo list:
=> fix: mozilla name typo

pollbot/views/utilities.py, tests/test_oas.py, tests/test_views.py
-------------
!!! HELLO !!!
-------------
Thank you for taking the time to contribute, we really appreciate it.
If it is your first time, please know that you are really welcome !!
--------------------------
Are you adding a new task?
--------------------------
If yes, you might want to have a look at this documentation and examples
https://github.com/mozilla/PollBot/wiki/Adding-a-task-for-PollBot
------------------------
DELETE EVERYTHING BEFORE
------------------------
Adding a task todo list:
=> update yaml.safe_load uses (safe_load is deprecated)

requirements.in, requirements.txt
-------------
!!! HELLO !!!
-------------
Thank you for taking the time to contribute, we really appreciate it.
If it is your first time, please know that you are really welcome !!
--------------------------
Are you adding a new task?
--------------------------
If yes, you might want to have a look at this documentation and examples
https://github.com/mozilla/PollBot/wiki/Adding-a-task-for-PollBot
------------------------
DELETE EVERYTHING BEFORE
------------------------
Adding a task todo list:
=> update pytest based on https://github.com/pytest-dev/pytest/issues/12269
